name: gottcha2
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.9
  - minimap2>=2.27
  - samtools
  - pandas
  - numpy
  - biom-format>=2.1.7
  - requests
  - tqdm
  - pysam
  - sylph